#!/bin/bash
echo "The first Parameter is $1"
echo "The second Parameter is $2"
echo " The addition of two parameters is : `expr $1 + $2`"
echo "The Parameters are: $*"
echo "The Parameters are: $@"
echo "The no.of Parameters are: $#"
echo "The script name is: $0"
echo " The process id is: $$"
echo "The exit status of prev. cmd is : $?"
echo "The process id of background running process: $!"
